[workspace]
members = [
    "apps/desktop",
    "crates/krkr-audio",
    "crates/krkr-core",
    "crates/krkr-kag",
    "crates/krkr-platform",
    "crates/krkr-render",
    "crates/krkr-engine",
    "crates/krkr-tjs2",
    "crates/krkr-xp3",
]
resolver = "3"

[workspace.package]
edition = "2024"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
bytemuck = { version = "1.24.0", features = ["derive"] }
cpal = "=0.17.3"
flate2 = { version = "1.0", default-features = false, features = ["rust_backend"] }
pollster = "0.4.0"
rfd = "=0.17.2"
symphonia = { version = "=0.5.5", default-features = false, features = ["aac", "flac", "isomp4", "mp3", "ogg", "vorbis", "wav"] }
wgpu = "=29.0.1"
winit = "=0.30.13"

krkr-audio = { path = "crates/krkr-audio" }
krkr-core = { path = "crates/krkr-core" }
krkr-kag = { path = "crates/krkr-kag" }
krkr-platform = { path = "crates/krkr-platform" }
krkr-render = { path = "crates/krkr-render" }
krkr-engine = { path = "crates/krkr-engine" }
krkr-tjs2 = { path = "crates/krkr-tjs2" }
krkr-xp3 = { path = "crates/krkr-xp3" }
