[workspace]
members = [
    "apps/desktop",
    "crates/krkr-audio",
    "crates/krkr-core",
    "crates/krkr-font",
    "crates/krkr-kag",
    "crates/krkr-platform",
    "crates/krkr-render",
    "crates/krkr-engine",
    "crates/krkr-tjs2",
    "crates/krkr-xp3",
]
resolver = "3"

[workspace.package]
edition = "2024"
license = "AGPL-3.0-or-later"
license-file = "LICENSE"

[workspace.dependencies]
bytemuck = { version = "1.24.0", features = ["derive"] }
cpal = "=0.17.3"
encoding_rs = "0.8.35"
flate2 = { version = "1.0", default-features = false, features = ["rust_backend"] }
image = { version = "0.25.8", default-features = false, features = ["bmp", "jpeg", "png"] }
fontdb = "0.23.0"
kira = { version = "=0.12.0", default-features = false, features = ["cpal", "mp3", "ogg", "vorbis", "wav", "flac", "aac", "isomp4"] }
memmap2 = "0.9.9"
pollster = "0.4.0"
rfd = "=0.17.2"
swash = "0.2.7"
symphonia = { version = "=0.5.5", default-features = false, features = ["aac", "flac", "isomp4", "mp3", "ogg", "vorbis", "wav"] }
wgpu = "=29.0.1"
winit = "=0.30.13"

krkr-audio = { path = "crates/krkr-audio" }
krkr-core = { path = "crates/krkr-core" }
krkr-font = { path = "crates/krkr-font" }
krkr-kag = { path = "crates/krkr-kag" }
krkr-platform = { path = "crates/krkr-platform" }
krkr-render = { path = "crates/krkr-render" }
krkr-engine = { path = "crates/krkr-engine" }
krkr-tjs2 = { path = "crates/krkr-tjs2" }
krkr-xp3 = { path = "crates/krkr-xp3" }
