[package]
name = "krkr-assets"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
encoding_rs.workspace = true
flate2.workspace = true
krkr-core.workspace = true
krkr-tjs2.workspace = true
krkr-xp3.workspace = true
memmap2.workspace = true
serde.workspace = true
serde_json.workspace = true
