//! Platform-neutral asset catalogue and the native static-package adapter.
//!
//! The runtime only talks to [`krkr_core::AssetScheduler`].  Browser hosts can
//! implement the same polling contract around `fetch`, while this crate
//! provides a filesystem implementation for desktop, terminal and tests.
//! Publication is intentionally thin: files retain logical KRKR paths and
//! the CDN/object store owns caching, compression and delivery policy. There
//! is no Kirakira-owned chunk, bundle or content-addressed package format.

use std::{
    collections::{BTreeMap, BTreeSet},
    fs,
    io::{self, Read},
    path::{Path, PathBuf},
    sync::{Arc, Mutex, mpsc},
    thread,
};

use krkr_core::{AssetEvent, AssetKind, AssetRequestId, AssetScheduler};
use serde::{Deserialize, Serialize};

/// Version of the semantic-path Web manifest. This deliberately remains v1;
/// there is no local CAS/bundle format for Web publications.
pub const WEB_PACKAGE_FORMAT: u32 = 1;

/// Web publication manifest. Every entry points at a real file below the
/// package root using its semantic KRKR storage path. The manifest only
/// carries metadata needed for lookup and bootstrap; CDN cache keys and
/// compression are deliberately outside this format.
#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub struct WebManifest {
    pub format: u32,
    pub game: String,
    pub engine: String,
    pub bootstrap: Vec<String>,
    /// Explicit KAG scenario to enter after bootstrap.  Web hosts must not
    /// infer an entry from conventional filenames because those files can be
    /// dispatchers (for example a game's first-run flow) rather than the
    /// first visible title screen.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub entry: Option<String>,
    pub entries: BTreeMap<String, WebManifestEntry>,
    /// Canonical logical-name aliases generated by the publisher. Keys are
    /// either a normalized logical path or `kind|path` for an extensionless
    /// request whose asset kind disambiguates multiple files.
    #[serde(default, skip_serializing_if = "BTreeMap::is_empty")]
    pub aliases: BTreeMap<String, String>,
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub struct WebManifestEntry {
    /// Relative URL/path in the published package. Usually equal to the map
    /// key, but explicit so a deployment can remap a logical name safely.
    pub path: String,
    pub kind: String,
    pub size: u64,
    pub mime: String,
    #[serde(default)]
    pub preload: bool,
}

impl WebManifest {
    pub fn to_json(&self) -> Result<String, serde_json::Error> {
        serde_json::to_string_pretty(self)
    }

    pub fn from_json(json: &str) -> Result<Self, serde_json::Error> {
        serde_json::from_str(json)
    }

    pub fn entry(&self, path: &str) -> Option<&WebManifestEntry> {
        let normalized = normalize_path(path);
        if let Some(key) = self.aliases.get(&normalized.to_ascii_lowercase()) {
            return self.entries.get(key);
        }
        // The publisher always indexes canonical paths. Direct lookup keeps
        // small hand-authored fixtures useful without reintroducing a hot-path
        // manifest scan or a historical-format fallback.
        self.entries.get(&normalized)
    }

    /// Resolves an extensionless KRKR storage name when the manifest contains
    /// multiple files sharing the same stem (for example `waitglyph.asd` and
    /// `waitglyph.png`). The caller's asset kind disambiguates the intended
    /// member while retaining the ambiguity protection of [`Self::entry`].
    pub fn entry_for_kind(&self, path: &str, kind: &str) -> Option<&WebManifestEntry> {
        let normalized = normalize_path(path);
        if let Some(key) = self.aliases.get(&format!(
            "{}|{}",
            kind.to_ascii_lowercase(),
            normalized.to_ascii_lowercase()
        )) {
            return self.entries.get(key);
        }
        self.entry(path)
            .filter(|entry| entry.kind.eq_ignore_ascii_case(kind))
    }
}

fn build_web_aliases(entries: &BTreeMap<String, WebManifestEntry>) -> BTreeMap<String, String> {
    let mut candidates = BTreeMap::<String, Option<String>>::new();
    let mut ui_candidates = BTreeMap::<String, Option<String>>::new();
    // A bare KRKR storage name first addresses a file at the project root;
    // configured auto paths are only searched after that direct candidate.
    // Preserve the same deterministic precedence in the published alias
    // index when a package contains both `mainwindow.tjs` and
    // `system/mainwindow.tjs`.
    let root_paths = entries
        .iter()
        .flat_map(|(key, entry)| [key.as_str(), entry.path.as_str()])
        .map(normalize_path)
        .filter(|path| !path.is_empty() && !path.contains('/'))
        .map(|path| path.to_ascii_lowercase())
        .collect::<BTreeSet<_>>();
    for (key, entry) in entries {
        let key_path = normalize_path(key);
        let entry_path = normalize_path(&entry.path);
        for path in [key_path, entry_path] {
            if path.is_empty() {
                continue;
            }
            insert_unique_alias(&mut candidates, path.clone(), key);
            insert_unique_alias(
                &mut candidates,
                format!("{}|{}", entry.kind.to_ascii_lowercase(), path),
                key,
            );

            let Some((stem, _extension)) = path.rsplit_once('.').and_then(|(stem, ext)| {
                (!stem.is_empty() && !ext.is_empty() && !stem.ends_with('/')).then_some((stem, ext))
            }) else {
                continue;
            };
            insert_unique_alias(
                &mut candidates,
                format!("{}|{}", entry.kind.to_ascii_lowercase(), stem),
                key,
            );
            let basename = stem.rsplit('/').next().unwrap_or(stem);
            let basename_with_extension = path.rsplit('/').next().unwrap_or(&path);
            let root_basename = root_paths.contains(&basename_with_extension.to_ascii_lowercase());
            let root_stem = root_paths.contains(&basename.to_ascii_lowercase());
            let is_preferred_ui_image =
                path.starts_with("uipsd/") && entry.kind.eq_ignore_ascii_case("image");
            if !root_basename || is_preferred_ui_image {
                insert_unique_alias(
                    &mut candidates,
                    format!("{}|{}", entry.kind.to_ascii_lowercase(), basename),
                    key,
                );
                insert_unique_alias(&mut candidates, basename_with_extension.to_string(), key);
            }
            if !root_stem || is_preferred_ui_image {
                insert_unique_alias(&mut candidates, stem.to_string(), key);
                insert_unique_alias(&mut candidates, basename.to_string(), key);
            }
            if path.starts_with("uipsd/") {
                for alias in [
                    path.clone(),
                    format!("{}|{}", entry.kind.to_ascii_lowercase(), path),
                    format!("{}|{}", entry.kind.to_ascii_lowercase(), stem),
                    format!("{}|{}", entry.kind.to_ascii_lowercase(), basename),
                    basename_with_extension.to_string(),
                    stem.to_string(),
                    basename.to_string(),
                ] {
                    insert_unique_alias(&mut ui_candidates, alias, key);
                }
            }
        }
    }
    candidates
        .into_iter()
        .filter_map(|(alias, key)| {
            key.or_else(|| ui_candidates.get(&alias).cloned().flatten())
                .map(|key| (alias, key))
        })
        .collect()
}

fn insert_unique_alias(
    candidates: &mut BTreeMap<String, Option<String>>,
    alias: String,
    key: &str,
) {
    let alias = alias.to_ascii_lowercase();
    match candidates.get_mut(&alias) {
        Some(existing @ Some(_)) if existing.as_deref() != Some(key) => *existing = None,
        Some(None) => {}
        Some(Some(_)) => {}
        None => {
            candidates.insert(alias, Some(key.to_string()));
        }
    }
}

/// Reads assets from a directory and completes requests on the next `poll`.
/// It is intentionally independent of the engine's ProjectStorage, making it
/// suitable for desktop, Web and future mobile hosts.
#[derive(Debug)]
pub struct NativeAssetStore {
    root: PathBuf,
    request_tx: mpsc::Sender<NativeAssetRequest>,
    event_rx: mpsc::Receiver<AssetEvent>,
    cancelled: Arc<Mutex<BTreeSet<AssetRequestId>>>,
    pending_ids: BTreeSet<AssetRequestId>,
    next_request_id: u64,
    revision: u64,
}

struct NativeAssetRequest {
    id: AssetRequestId,
    path: String,
    kind: AssetKind,
}

impl NativeAssetStore {
    pub fn new(root: impl Into<PathBuf>) -> Self {
        let root = root.into();
        let (request_tx, request_rx) = mpsc::channel::<NativeAssetRequest>();
        let (event_tx, event_rx) = mpsc::channel::<AssetEvent>();
        let cancelled = Arc::new(Mutex::new(BTreeSet::new()));
        let worker_cancelled = Arc::clone(&cancelled);
        let worker_root = root.clone();
        let _ = thread::Builder::new()
            .name("kirakira-asset-worker".to_string())
            .spawn(move || {
                while let Ok(request) = request_rx.recv() {
                    if take_cancelled(&worker_cancelled, request.id) {
                        continue;
                    }
                    let event = match read_asset_path(&worker_root, &request.path) {
                        Ok(bytes) => AssetEvent::Ready {
                            id: request.id,
                            path: request.path,
                            kind: request.kind,
                            data: Arc::from(bytes),
                        },
                        Err(error) => AssetEvent::Failed {
                            id: request.id,
                            path: request.path,
                            kind: request.kind,
                            message: error.to_string(),
                        },
                    };
                    if take_cancelled(&worker_cancelled, request.id) {
                        continue;
                    }
                    if event_tx.send(event).is_err() {
                        break;
                    }
                }
            });
        Self {
            root,
            request_tx,
            event_rx,
            cancelled,
            pending_ids: BTreeSet::new(),
            next_request_id: 0,
            revision: 1,
        }
    }

    pub fn root(&self) -> &Path {
        &self.root
    }
}

impl AssetScheduler for NativeAssetStore {
    fn request(&mut self, path: &str, kind: AssetKind) -> AssetRequestId {
        self.next_request_id = self.next_request_id.saturating_add(1);
        let id = AssetRequestId(self.next_request_id);
        self.pending_ids.insert(id);
        if self
            .request_tx
            .send(NativeAssetRequest {
                id,
                path: path.to_string(),
                kind,
            })
            .is_err()
        {
            self.pending_ids.remove(&id);
        }
        id
    }

    fn poll(&mut self) -> Vec<AssetEvent> {
        let mut events = Vec::new();
        while let Ok(event) = self.event_rx.try_recv() {
            let id = match &event {
                AssetEvent::Ready { id, .. } | AssetEvent::Failed { id, .. } => *id,
            };
            self.pending_ids.remove(&id);
            if !self
                .cancelled
                .lock()
                .map(|mut ids| !ids.remove(&id))
                .unwrap_or(false)
            {
                continue;
            }
            events.push(event);
        }
        events
    }

    fn cancel(&mut self, id: AssetRequestId) -> bool {
        if !self.pending_ids.remove(&id) {
            return false;
        }
        self.cancelled
            .lock()
            .map(|mut ids| ids.insert(id))
            .unwrap_or(false)
    }

    fn revision(&self) -> u64 {
        self.revision
    }
}

fn read_asset_path(root: &Path, path: &str) -> io::Result<Vec<u8>> {
    let normalized = normalize_path(path);
    if normalized.is_empty() || normalized.split('/').any(|part| part == "..") {
        return Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            "asset path escapes package root",
        ));
    }
    fs::read(root.join(normalized))
}

fn take_cancelled(cancelled: &Mutex<BTreeSet<AssetRequestId>>, id: AssetRequestId) -> bool {
    cancelled
        .lock()
        .map(|mut ids| ids.remove(&id))
        .unwrap_or(false)
}

/// Publishes a directory as a semantic-path Web package (format v1).
///
/// Files are copied to the output using their original relative names. No
/// chunks, content hashes, bundles or archive indexes are generated; those
/// concerns belong to the CDN/object store. With `extract_xp3`, archive
/// members are materialized as normal files because a browser cannot use the
/// native seekable XP3 provider over a static URL.
pub fn pack_web_directory(
    input: impl AsRef<Path>,
    output: impl AsRef<Path>,
    extract_xp3: bool,
) -> io::Result<WebManifest> {
    pack_web_directory_with_entry(input, output, extract_xp3, None)
}

/// Publishes a semantic-path Web package and records its explicit KAG entry.
/// Keeping the entry in the manifest makes a static publication self-contained
/// while leaving runtime code free of filename heuristics.
pub fn pack_web_directory_with_entry(
    input: impl AsRef<Path>,
    output: impl AsRef<Path>,
    extract_xp3: bool,
    entry: Option<&str>,
) -> io::Result<WebManifest> {
    let input = fs::canonicalize(input.as_ref())?;
    let output_path = output.as_ref();
    let output =
        if output_path.exists() {
            fs::canonicalize(output_path)?
        } else {
            let parent = output_path.parent().unwrap_or_else(|| Path::new("."));
            fs::create_dir_all(parent)?;
            fs::canonicalize(parent)?.join(output_path.file_name().ok_or_else(|| {
                io::Error::new(io::ErrorKind::InvalidInput, "invalid output path")
            })?)
        };
    if input == output {
        return Err(io::Error::new(
            io::ErrorKind::InvalidInput,
            "Web package output must differ from the input directory",
        ));
    }

    let mut files = Vec::new();
    let excluded = output.strip_prefix(&input).ok().map(Path::to_path_buf);
    collect_files(&input, &input, &mut files, excluded.as_deref())?;
    files.sort();
    let mut assets = BTreeMap::<String, Vec<u8>>::new();
    for relative in files {
        let path = input.join(&relative);
        if extract_xp3
            && path
                .extension()
                .is_some_and(|ext| ext.eq_ignore_ascii_case("xp3"))
        {
            let archive = krkr_xp3::Xp3Archive::open_file(&path)
                .map_err(|error| io::Error::new(io::ErrorKind::InvalidData, error.to_string()))?;
            for index in 0..archive.entries().len() {
                let entry = archive.entries().get(index).expect("entry index");
                let mut stream = archive.open_by_index(index).map_err(|error| {
                    io::Error::new(io::ErrorKind::InvalidData, error.to_string())
                })?;
                let mut bytes = Vec::with_capacity(entry.original_size as usize);
                stream.read_to_end(&mut bytes)?;
                let member = normalize_path(&entry.name);
                if member.is_empty() || member.split('/').any(|part| part == "..") {
                    return Err(io::Error::new(
                        io::ErrorKind::InvalidData,
                        format!("XP3 member escapes package root: {}", entry.name),
                    ));
                }
                assets.insert(member, bytes);
            }
        } else {
            assets.insert(normalize_path(&relative.to_string_lossy()), fs::read(path)?);
        }
    }

    // A publish directory is an artifact, so stale files from an earlier
    // package must not survive and be served by a static host.  Clear only
    // the validated output directory after all source bytes have been read;
    // this also keeps the supported "output nested under input" layout safe.
    clear_directory_contents(&output)?;

    let mut entries = BTreeMap::new();
    for (path, bytes) in assets {
        let mime = mime_for_path(&path).to_string();
        let kind = asset_kind_for_path(&path).to_string();
        let lower_path = path.to_ascii_lowercase();
        // Keep the initial request bounded to the conventional startup
        // files. Every other script, UI resource and media file is fetched
        // through the lazy AssetScheduler when the engine first touches it.
        // The engine must see its persisted system flags while executing the
        // startup script.  Keep these tiny metadata files in the synchronous
        // bootstrap set; all game media, UI and scenario resources remain
        // lazy.  In particular, `datasu.ksd` carries flags such as GINKA's
        // `sf.notFirst`, which decides whether the opening flow shows the
        // first-run language/configuration screen.
        let preload = matches!(
            lower_path.as_str(),
            "startup.tjs"
                | "startup.ks"
                | "enginerev.ini"
                | "savedata/datasu.ksd"
                | "savedata/datasc.ksd"
                | "savedata/data_anchor.ksd"
                | "savedata/savecheck"
        );
        let destination = output.join(&path);
        if let Some(parent) = destination.parent() {
            fs::create_dir_all(parent)?;
        }
        fs::write(&destination, &bytes)?;
        entries.insert(
            path.clone(),
            WebManifestEntry {
                path,
                kind,
                size: bytes.len() as u64,
                mime,
                preload,
            },
        );
    }

    let bootstrap = entries
        .iter()
        .filter(|(_, entry)| entry.preload)
        .map(|(path, _)| path.clone())
        .collect();
    let game = input
        .file_name()
        .and_then(|name| name.to_str())
        .unwrap_or("game")
        .to_string();
    let entry = entry
        .map(normalize_path)
        .filter(|path| !path.is_empty())
        .map(|path| {
            if path.starts_with('/') || path.split('/').any(|part| part == "..") {
                return Err(io::Error::new(
                    io::ErrorKind::InvalidInput,
                    format!("invalid Web entry path: {path}"),
                ));
            }
            let Some((key, _)) = entries.iter().find(|(key, value)| {
                normalize_path(key).eq_ignore_ascii_case(&path)
                    || normalize_path(&value.path).eq_ignore_ascii_case(&path)
            }) else {
                return Err(io::Error::new(
                    io::ErrorKind::InvalidInput,
                    format!("Web entry is not present in package: {path}"),
                ));
            };
            Ok(key.clone())
        })
        .transpose()?;
    let aliases = build_web_aliases(&entries);
    let manifest = WebManifest {
        format: WEB_PACKAGE_FORMAT,
        game,
        engine: "krkrz".to_string(),
        bootstrap,
        entry,
        entries,
        aliases,
    };
    fs::write(
        output.join("manifest.json"),
        manifest
            .to_json()
            .map_err(|error| io::Error::new(io::ErrorKind::InvalidData, error.to_string()))?,
    )?;
    Ok(manifest)
}

fn clear_directory_contents(path: &Path) -> io::Result<()> {
    fs::create_dir_all(path)?;
    for entry in fs::read_dir(path)? {
        let entry = entry?;
        let child = entry.path();
        if child.is_dir() {
            fs::remove_dir_all(child)?;
        } else {
            fs::remove_file(child)?;
        }
    }
    Ok(())
}

fn asset_kind_for_path(path: &str) -> &'static str {
    match Path::new(path)
        .extension()
        .and_then(|ext| ext.to_str())
        .unwrap_or("")
        .to_ascii_lowercase()
        .as_str()
    {
        "tjs" | "ks" | "pbd" => "script",
        "png" | "jpg" | "jpeg" | "webp" | "tlg" | "bmp" => "image",
        "wav" | "ogg" | "mp3" | "opus" | "flac" => "audio",
        "wmv" | "mp4" | "m4v" | "avi" | "webm" | "ogv" | "mov" | "mkv" => "video",
        _ => "binary",
    }
}

fn mime_for_path(path: &str) -> &'static str {
    match Path::new(path)
        .extension()
        .and_then(|ext| ext.to_str())
        .unwrap_or("")
        .to_ascii_lowercase()
        .as_str()
    {
        "tjs" | "ks" | "pbd" => "text/plain",
        "png" => "image/png",
        "jpg" | "jpeg" => "image/jpeg",
        "webp" => "image/webp",
        "tlg" => "application/octet-stream",
        "bmp" => "image/bmp",
        "wav" => "audio/wav",
        "ogg" => "audio/ogg",
        "mp3" => "audio/mpeg",
        "flac" => "audio/flac",
        "wmv" => "video/x-ms-wmv",
        "mp4" => "video/mp4",
        "m4v" => "video/mp4",
        "webm" => "video/webm",
        "ogv" => "video/ogg",
        "mov" => "video/quicktime",
        "mkv" => "video/x-matroska",
        _ => "application/octet-stream",
    }
}

fn collect_files(
    root: &Path,
    current: &Path,
    output: &mut Vec<PathBuf>,
    excluded: Option<&Path>,
) -> io::Result<()> {
    for entry in fs::read_dir(current)? {
        let entry = entry?;
        let path = entry.path();
        if path.is_dir() {
            let relative = path.strip_prefix(root).ok();
            if excluded.is_some_and(|excluded| relative == Some(excluded)) {
                continue;
            }
            collect_files(root, &path, output, excluded)?;
        } else if path.is_file() {
            if let Ok(relative) = path.strip_prefix(root) {
                output.push(relative.to_path_buf());
            }
        }
    }
    Ok(())
}

fn normalize_path(path: &str) -> String {
    path.replace('\\', "/")
        .split('/')
        .filter(|part| !part.is_empty() && *part != ".")
        .collect::<Vec<_>>()
        .join("/")
}

#[cfg(test)]
mod tests {
    use std::{
        sync::atomic::{AtomicU64, Ordering},
        time::{SystemTime, UNIX_EPOCH},
    };

    use super::*;

    #[test]
    fn native_store_rejects_parent_traversal() {
        let mut store = NativeAssetStore::new(temp_root());
        store.request("../outside", AssetKind::Binary);
        let mut events = Vec::new();
        for _ in 0..100 {
            events.extend(store.poll());
            if !events.is_empty() {
                break;
            }
            std::thread::sleep(std::time::Duration::from_millis(1));
        }
        assert!(matches!(events.as_slice(), [AssetEvent::Failed { .. }]));
    }

    #[test]
    fn web_manifest_preserves_semantic_paths() {
        let root = temp_root();
        let output = root.join("out");
        fs::create_dir_all(&root).expect("create fixture");
        fs::write(root.join("startup.tjs"), b"System.init();").expect("write script");
        fs::write(root.join("large.bin"), vec![7u8; 128]).expect("write large fixture");
        let manifest = pack_web_directory(&root, &output, false).expect("pack web fixture");
        assert_eq!(manifest.format, WEB_PACKAGE_FORMAT);
        assert_eq!(manifest.entry, None);
        assert_eq!(manifest.bootstrap, vec!["startup.tjs"]);
        let startup = manifest.entry("startup.tjs").expect("startup entry");
        assert_eq!(startup.kind, "script");
        assert_eq!(startup.path, "startup.tjs");
        let large = manifest.entry("large.bin").expect("large entry");
        assert_eq!(large.path, "large.bin");
        assert!(output.join(&large.path).is_file());
        assert!(!output.join("objects").exists());
        assert!(!output.join("bundles").exists());
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn web_publish_clears_stale_output_files() {
        let root = temp_root();
        let output = root.join("out");
        fs::create_dir_all(output.join("stale/nested")).expect("create stale output");
        fs::write(output.join("stale/nested/old.bin"), b"old").expect("write stale output");
        fs::write(root.join("startup.tjs"), b"System.init();").expect("write script");

        pack_web_directory(&root, &output, false).expect("pack web fixture");
        assert!(!output.join("stale").exists());
        assert!(output.join("startup.tjs").is_file());
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn web_manifest_bootstraps_system_save_metadata() {
        let root = temp_root();
        let output = root.join("out");
        fs::create_dir_all(root.join("savedata")).expect("create save directory");
        fs::write(root.join("startup.tjs"), b"System.init();").expect("write startup");
        fs::write(root.join("savedata/datasu.ksd"), b"(const) %[]").expect("write system save");
        fs::write(root.join("savedata/bookmark.ksd"), b"(const) %[]").expect("write bookmark");

        let manifest = pack_web_directory(&root, &output, false).expect("pack web fixture");
        assert!(manifest.bootstrap.contains(&"startup.tjs".to_string()));
        assert!(
            manifest
                .bootstrap
                .contains(&"savedata/datasu.ksd".to_string())
        );
        assert!(
            !manifest
                .bootstrap
                .contains(&"savedata/bookmark.ksd".to_string())
        );
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn web_manifest_records_and_validates_explicit_entry() {
        let root = temp_root();
        let output = root.join("out");
        fs::write(root.join("sysscn/first.ks"), b"[s]").expect_err("parent is absent");
        fs::create_dir_all(root.join("sysscn")).expect("create scenario directory");
        fs::write(root.join("sysscn/first.ks"), b"[s]").expect("write scenario");
        let manifest =
            pack_web_directory_with_entry(&root, &output, false, Some("SYSSCN/FIRST.KS"))
                .expect("pack web fixture");
        assert_eq!(manifest.entry.as_deref(), Some("sysscn/first.ks"));

        let missing =
            pack_web_directory_with_entry(&root, root.join("missing"), false, Some("no.ks"));
        assert!(missing.is_err());
        let _ = fs::remove_dir_all(root);
    }

    #[test]
    fn web_manifest_resolves_krkr_extensionless_image_names() {
        let entry = WebManifestEntry {
            path: "uipsd/menu_sprite.tlg".to_string(),
            kind: "image".to_string(),
            size: 1,
            mime: "image/tlg".to_string(),
            preload: false,
        };
        let mut manifest = WebManifest {
            format: WEB_PACKAGE_FORMAT,
            game: "fixture".to_string(),
            engine: "kirakira".to_string(),
            bootstrap: Vec::new(),
            entry: None,
            entries: [("uipsd/menu_sprite.tlg".to_string(), entry)]
                .into_iter()
                .collect(),
            aliases: BTreeMap::new(),
        };
        manifest.aliases = build_web_aliases(&manifest.entries);
        assert!(manifest.entry("menu_sprite").is_some());
        assert!(manifest.entry("menu_sprite.tlg").is_some());
    }

    #[test]
    fn web_manifest_kind_resolves_ambiguous_extensionless_names() {
        let image = WebManifestEntry {
            path: "uipsd/waitglyph.png".to_string(),
            kind: "image".to_string(),
            size: 1,
            mime: "image/png".to_string(),
            preload: false,
        };
        let sidecar = WebManifestEntry {
            path: "uipsd/waitglyph.asd".to_string(),
            kind: "binary".to_string(),
            size: 1,
            mime: "application/octet-stream".to_string(),
            preload: false,
        };
        let mut manifest = WebManifest {
            format: WEB_PACKAGE_FORMAT,
            game: "fixture".to_string(),
            engine: "kirakira".to_string(),
            bootstrap: Vec::new(),
            entry: None,
            entries: [
                ("uipsd/waitglyph.png".to_string(), image),
                ("uipsd/waitglyph.asd".to_string(), sidecar),
            ]
            .into_iter()
            .collect(),
            aliases: BTreeMap::new(),
        };
        manifest.aliases = build_web_aliases(&manifest.entries);
        assert!(manifest.entry("waitglyph").is_none());
        assert_eq!(
            manifest.entry_for_kind("waitglyph", "image").unwrap().kind,
            "image"
        );
    }

    #[test]
    fn web_manifest_kind_prefers_ui_auto_path_for_duplicate_images() {
        let entry = |path: &str| WebManifestEntry {
            path: path.to_string(),
            kind: "image".to_string(),
            size: 1,
            mime: "image/tlg".to_string(),
            preload: false,
        };
        let mut manifest = WebManifest {
            format: WEB_PACKAGE_FORMAT,
            game: "fixture".to_string(),
            engine: "kirakira".to_string(),
            bootstrap: Vec::new(),
            entry: None,
            entries: [
                ("title__pack.tlg".to_string(), entry("title__pack.tlg")),
                (
                    "uipsd/title__pack.tlg".to_string(),
                    entry("uipsd/title__pack.tlg"),
                ),
            ]
            .into_iter()
            .collect(),
            aliases: BTreeMap::new(),
        };
        manifest.aliases = build_web_aliases(&manifest.entries);
        assert_eq!(
            manifest
                .entry_for_kind("title__pack", "image")
                .expect("UI image alias")
                .path,
            "uipsd/title__pack.tlg"
        );
    }

    #[test]
    fn web_manifest_bare_name_prefers_project_root_over_auto_path() {
        let script = |path: &str| WebManifestEntry {
            path: path.to_string(),
            kind: "script".to_string(),
            size: 1,
            mime: "application/octet-stream".to_string(),
            preload: false,
        };
        let mut manifest = WebManifest {
            format: WEB_PACKAGE_FORMAT,
            game: "fixture".to_string(),
            engine: "kirakira".to_string(),
            bootstrap: Vec::new(),
            entry: None,
            entries: [
                ("mainwindow.tjs".to_string(), script("mainwindow.tjs")),
                (
                    "system/mainwindow.tjs".to_string(),
                    script("system/mainwindow.tjs"),
                ),
            ]
            .into_iter()
            .collect(),
            aliases: BTreeMap::new(),
        };
        manifest.aliases = build_web_aliases(&manifest.entries);
        assert_eq!(
            manifest.entry("MainWindow.tjs").unwrap().path,
            "mainwindow.tjs"
        );
        assert_eq!(
            manifest
                .entry_for_kind("MainWindow.tjs", "script")
                .unwrap()
                .path,
            "mainwindow.tjs"
        );
    }

    fn temp_root() -> PathBuf {
        static NEXT: AtomicU64 = AtomicU64::new(0);
        let nanos = SystemTime::now()
            .duration_since(UNIX_EPOCH)
            .expect("clock")
            .as_nanos();
        let serial = NEXT.fetch_add(1, Ordering::Relaxed);
        std::env::temp_dir().join(format!("kirakira-assets-{nanos}-{serial}"))
    }
}
