use krkr_tjs2::runtime::{Runtime, Variant};

use crate::host::KrkrHost;

pub(crate) fn install_tvp_constants(runtime: &mut Runtime<KrkrHost>) {
    for (name, value) in [
        ("bsNone", 0),
        ("bsSingle", 1),
        ("bsSizeable", 2),
        ("bsDialog", 3),
        ("bsToolWindow", 4),
        ("bsSizeToolWin", 5),
        ("utNormal", 0),
        ("utEntire", 1),
        ("mbLeft", 0),
        ("mbRight", 1),
        ("mbMiddle", 2),
        ("mbX1", 3),
        ("mbX2", 4),
        ("ssShift", 1 << 0),
        ("ssAlt", 1 << 1),
        ("ssCtrl", 1 << 2),
        ("ssLeft", 1 << 3),
        ("ssRight", 1 << 4),
        ("ssMiddle", 1 << 5),
        ("ssDouble", 1 << 6),
        ("ssRepeat", 1 << 7),
        ("ltBinder", 0),
        ("ltCoverRect", 1),
        ("ltOpaque", 1),
        ("ltTransparent", 2),
        ("ltAlpha", 2),
        ("ltAdditive", 3),
        ("ltSubtractive", 4),
        ("ltMultiplicative", 5),
        ("ltEffect", 6),
        ("ltFilter", 7),
        ("ltDodge", 8),
        ("ltDarken", 9),
        ("ltLighten", 10),
        ("ltScreen", 11),
        ("ltAddAlpha", 12),
        ("ltPsNormal", 13),
        ("ltPsAdditive", 14),
        ("ltPsSubtractive", 15),
        ("ltPsMultiplicative", 16),
        ("ltPsScreen", 17),
        ("ltPsOverlay", 18),
        ("ltPsHardLight", 19),
        ("ltPsSoftLight", 20),
        ("omAuto", 128),
        ("dfBoth", 0),
        ("dfAlpha", 0),
        ("dfMain", 1),
        ("dfOpaque", 1),
        ("dfMask", 2),
        ("dfProvince", 3),
        ("dfAddAlpha", 4),
        ("dfAuto", 128),
        ("htMask", 0),
        ("htProvince", 1),
        ("atmNormal", 0),
        ("atmExclusive", 1),
        ("atmAtIdle", 2),
        ("cbfText", 1),
        ("clIdle", 5),
        ("clDeactivate", 10),
        ("clMinimize", 15),
        ("clAll", 100),
        ("vomOverlay", 0),
        ("vomLayer", 1),
        ("vomMixer", 2),
        ("vomMFEVR", 3),
        ("sgfmNeverMute", 0),
        ("sgfmMuteOnMinimize", 1),
        ("sgfmMuteOnDeactivate", 2),
        ("faReadOnly", 0x01),
        ("faHidden", 0x02),
        ("faSysFile", 0x04),
        ("faVolumeID", 0x08),
        ("faDirectory", 0x10),
        ("faArchive", 0x20),
        ("faAnyFile", 0x3f),
        ("crDefault", 0),
        ("crNone", -1),
        ("crArrow", -2),
        ("clNone", 0x1fff_ffff),
        ("VK_ESCAPE", 0x1b),
        ("VK_RETURN", 0x0d),
        ("VK_SPACE", 0x20),
        ("VK_LEFT", 0x25),
        ("VK_UP", 0x26),
        ("VK_RIGHT", 0x27),
        ("VK_DOWN", 0x28),
    ] {
        runtime.set_global_member(name, Variant::Integer(value));
    }
}
