use krkr_tjs2::runtime::{Runtime, Variant};

use crate::host::KrkrHost;

pub(crate) fn install_tvp_constants(runtime: &mut Runtime<KrkrHost>) {
    for (name, value) in [
        ("bsNone", 0),
        ("bsSingle", 1),
        ("bsSizeable", 2),
        ("bsDialog", 3),
        ("bsToolWindow", 4),
        ("bsSizeToolWin", 5),
        ("utNormal", 0),
        ("utEntire", 1),
        ("mbLeft", 0),
        ("mbRight", 1),
        ("mbMiddle", 2),
        ("mbX1", 3),
        ("mbX2", 4),
        ("ssShift", 1 << 0),
        ("ssAlt", 1 << 1),
        ("ssCtrl", 1 << 2),
        ("ssLeft", 1 << 3),
        ("ssRight", 1 << 4),
        ("ssMiddle", 1 << 5),
        ("ssDouble", 1 << 6),
        ("ssRepeat", 1 << 7),
        ("ltBinder", 0),
        ("ltCoverRect", 1),
        ("ltOpaque", 1),
        ("ltTransparent", 2),
        ("ltAlpha", 2),
        ("ltAdditive", 3),
        ("ltSubtractive", 4),
        ("ltMultiplicative", 5),
        ("ltEffect", 6),
        ("ltFilter", 7),
        ("ltDodge", 8),
        ("ltDarken", 9),
        ("ltLighten", 10),
        ("ltScreen", 11),
        ("ltAddAlpha", 12),
        ("ltPsNormal", 13),
        ("ltPsAdditive", 14),
        ("ltPsSubtractive", 15),
        ("ltPsMultiplicative", 16),
        ("ltPsScreen", 17),
        ("ltPsOverlay", 18),
        ("ltPsHardLight", 19),
        ("ltPsSoftLight", 20),
        // `tTVPBlendOperationMode` aliases in `LayerIntf.h`. `omAuto` is the
        // only non-layer-type value; the rest share numbers with `lt*`.
        ("omOpaque", 1),
        ("omAlpha", 2),
        ("omAdditive", 3),
        ("omSubtractive", 4),
        ("omMultiplicative", 5),
        ("omDodge", 8),
        ("omDarken", 9),
        ("omLighten", 10),
        ("omScreen", 11),
        ("omAddAlpha", 12),
        ("omPsNormal", 13),
        ("omPsAdditive", 14),
        ("omPsSubtractive", 15),
        ("omPsMultiplicative", 16),
        ("omPsScreen", 17),
        ("omPsOverlay", 18),
        ("omPsHardLight", 19),
        ("omPsSoftLight", 20),
        ("omAuto", 128),
        ("sttLeft", 0),
        ("sttTop", 1),
        ("sttRight", 2),
        ("sttBottom", 3),
        ("ststNoStay", 0),
        ("ststStayDest", 1),
        ("ststStaySrc", 2),
        ("dfBoth", 0),
        ("dfAlpha", 0),
        ("dfMain", 1),
        ("dfOpaque", 1),
        ("dfMask", 2),
        ("dfProvince", 3),
        ("dfAddAlpha", 4),
        ("dfAuto", 128),
        ("htMask", 0),
        ("htProvince", 1),
        ("atmNormal", 0),
        ("atmExclusive", 1),
        ("atmAtIdle", 2),
        ("cbfText", 1),
        ("clIdle", 5),
        ("clDeactivate", 10),
        ("clMinimize", 15),
        ("clAll", 100),
        ("vomOverlay", 0),
        ("vomLayer", 1),
        ("vomMixer", 2),
        ("vomMFEVR", 3),
        ("perLoop", 0),
        ("perPeriod", 1),
        ("perPrepare", 2),
        ("perSegLoop", 3),
        ("sgfmNeverMute", 0),
        ("sgfmMuteOnMinimize", 1),
        ("sgfmMuteOnDeactivate", 2),
        ("faReadOnly", 0x01),
        ("faHidden", 0x02),
        ("faSysFile", 0x04),
        ("faVolumeID", 0x08),
        ("faDirectory", 0x10),
        ("faArchive", 0x20),
        ("faAnyFile", 0x3f),
        ("crDefault", 0),
        ("crNone", -1),
        ("crArrow", -2),
        // System colour identifiers, `ScriptMgnIntf.cpp:134` /
        // `visual/win32/TVPColor.h:6`. The `0x8000_0000` bit marks a
        // `GetSysColor` index; `TVPToActualColor` (`LayerImpl.cpp:21`) resolves
        // it, and the low byte is the index.
        ("clScrollBar", 0x8000_0000),
        ("clBackground", 0x8000_0001),
        ("clActiveCaption", 0x8000_0002),
        ("clInactiveCaption", 0x8000_0003),
        ("clMenu", 0x8000_0004),
        ("clWindow", 0x8000_0005),
        ("clWindowFrame", 0x8000_0006),
        ("clMenuText", 0x8000_0007),
        ("clWindowText", 0x8000_0008),
        ("clCaptionText", 0x8000_0009),
        ("clActiveBorder", 0x8000_000a),
        ("clInactiveBorder", 0x8000_000b),
        ("clAppWorkSpace", 0x8000_000c),
        ("clHighlight", 0x8000_000d),
        ("clHighlightText", 0x8000_000e),
        ("clBtnFace", 0x8000_000f),
        ("clBtnShadow", 0x8000_0010),
        ("clGrayText", 0x8000_0011),
        ("clBtnText", 0x8000_0012),
        ("clInactiveCaptionText", 0x8000_0013),
        ("clBtnHighlight", 0x8000_0014),
        ("cl3DDkShadow", 0x8000_0015),
        ("cl3DLight", 0x8000_0016),
        ("clInfoText", 0x8000_0017),
        ("clInfoBk", 0x8000_0018),
        // `tTVPBBStretchType` (`visual/LayerBitmapIntf.h:61`).
        ("stNearest", 0),
        ("stFastLinear", 1),
        ("stLinear", 2),
        ("stCubic", 3),
        ("stSemiFastLinear", 4),
        ("stFastCubic", 5),
        ("stLanczos2", 6),
        ("stFastLanczos2", 7),
        ("stLanczos3", 8),
        ("stFastLanczos3", 9),
        ("stSpline16", 10),
        ("stFastSpline16", 11),
        ("stSpline36", 12),
        ("stFastSpline36", 13),
        ("stAreaAvg", 14),
        ("stFastAreaAvg", 15),
        ("stGaussian", 16),
        ("stFastGaussian", 17),
        ("stBlackmanSinc", 18),
        ("stFastBlackmanSinc", 19),
        ("stTypeMask", 0x0000_ffff),
        ("stFlagMask", 0xffff_0000),
        ("stRefNoClip", 0x0001_0000),
        ("clNone", 0x1fff_ffff),
        ("clAdapt", 0x01ff_ffff),
        ("clPalIdx", 0x0300_0000),
        ("clAlphaMat", 0x0400_0000),
        ("VK_LBUTTON", 0x01),
        ("VK_RBUTTON", 0x02),
        ("VK_MBUTTON", 0x04),
        ("VK_BACK", 0x08),
        ("VK_TAB", 0x09),
        ("VK_RETURN", 0x0d),
        ("VK_SHIFT", 0x10),
        ("VK_CONTROL", 0x11),
        ("VK_MENU", 0x12),
        ("VK_ESCAPE", 0x1b),
        ("VK_SPACE", 0x20),
        ("VK_PRIOR", 0x21),
        ("VK_NEXT", 0x22),
        ("VK_END", 0x23),
        ("VK_HOME", 0x24),
        ("VK_LEFT", 0x25),
        ("VK_UP", 0x26),
        ("VK_RIGHT", 0x27),
        ("VK_DOWN", 0x28),
        ("VK_INSERT", 0x2d),
        ("VK_DELETE", 0x2e),
        ("VK_PADLEFT", 0x1b5),
        ("VK_PADUP", 0x1b6),
        ("VK_PADRIGHT", 0x1b7),
        ("VK_PADDOWN", 0x1b8),
        ("VK_PAD1", 0x1c0),
        ("VK_PAD2", 0x1c1),
        ("VK_PAD3", 0x1c2),
        ("VK_PADANY", 0x1df),
        ("tkdlNone", 0),
        ("tkdlSimple", 1),
        ("tkdlVerbose", 2),
        ("fsfFixedPitch", 1 << 0),
        ("fsfSameCharSet", 1 << 1),
        ("fsfNoVertical", 1 << 2),
        ("fsfTrueTypeOnly", 1 << 3),
        ("fsfUseFontFace", 1 << 4),
        ("fsfIgnoreSymbol", 1 << 5),
    ] {
        runtime.set_global_member(name, Variant::Integer(value));
    }
}
